# String functions 
num=input("Enter alpha numeric value")
an=num.isalnum()
print(an)
num=input("Enter alphabet value")
an=num.isalpha()
print(an)
dg=input("Enter digit")
an=dg.isdigit()
print(an)
sen=input("enter sentence")
an=sen.istitle()
print(an)
sen=input("enter sentence")
an=sen.title()
print(an)
sen=input("enter sentence")
an=sen.capitalize()
print(an)

