nm=input("enter string")
an=nm.islower()
print(an)
nm=input("enter string")
an=nm.isupper()
print(an)
nm=input("Enter string in upper case")
print(nm)
nm=nm.lower()
print("String in lower case",nm)
nm=input("Enter string in lower case")
print(nm)
nm=nm.upper()
print("String in upper case",nm)